/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dave.barnum' at '10/18/15 10:29 AM' with Gradle 2.4
 *
 * @author dave.barnum, @date 10/18/15 10:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
